# Generated by Django 3.2.8 on 2021-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='population',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
