# Generated by Django 3.2.8 on 2021-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211219_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
