# Generated by Django 3.2.8 on 2021-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='population',
            field=models.TextField(default=0, null=True),
        ),
    ]
