# Generated by Django 3.2.8 on 2021-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211222_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(max_length=150, null=True, upload_to='./static/images/'),
        ),
    ]
