# Generated by Django 3.2.8 on 2021-12-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='population',
            new_name='capacity',
        ),
    ]
