# Generated by Django 3.2.8 on 2021-12-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_population_blogpost_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='population',
            field=models.TextField(default=0, null=True),
        ),
    ]
