# Generated by Django 3.2.8 on 2021-12-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='capacity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='population',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
