# Generated by Django 3.2.8 on 2021-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211222_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourename', models.CharField(help_text='Name of the sender', max_length=200)),
                ('emailadd', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('leaveama', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'contact',
            },
        ),
    ]
