# Generated by Django 3.2.8 on 2021-12-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211226_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
