# Generated by Django 3.2.8 on 2021-12-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211227_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
