# Generated by Django 3.2.8 on 2021-12-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20211227_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
