# Generated by Django 3.2.8 on 2021-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_auto_increment_id_blogpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='palceId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
