# Generated by Django 3.2.8 on 2021-12-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20211227_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='palceId',
        ),
    ]
